import { NextResponse } from "next/server";
import { Resend } from "resend";

const resend = new Resend(process.env.RESEND_API_KEY);
const DEFAULT_FROM = "noreply@notyoungfashion.com";
const DEFAULT_TO = "markthecodershark@gmail.com";

interface AnalysisEmailRequest {
  email: string;
  tool: string;
  inputs: Record<string, unknown>;
  results: Record<string, unknown>;
  analysisHtml?: string;
}

export async function POST(request: Request) {
  try {
    const body: AnalysisEmailRequest = await request.json();
    const { email, tool, inputs, results, analysisHtml } = body;

    if (!email || !tool) {
      return NextResponse.json(
        { error: "Email and tool name are required" },
        { status: 400 }
      );
    }

    if (!process.env.RESEND_API_KEY) {
      return NextResponse.json(
        { error: "Email service not configured" },
        { status: 500 }
      );
    }

    const from = process.env.RESEND_FROM || DEFAULT_FROM;
    const adminTo = process.env.RESEND_TO || DEFAULT_TO;

    const toolNames: Record<string, string> = {
      "rent-estimate-calculator": "Rent Price Calculator",
      "vacancy-rate-calculator": "Vacancy Cost Calculator",
      "cap-rate-calculator": "Cap Rate Calculator",
      "renovation-roi": "Renovation ROI Calculator",
      "move-in-checklist": "Move-In Readiness Checklist",
    };

    const toolDisplayName = toolNames[tool] || tool;

    // Format results for email
    const formatValue = (value: unknown): string => {
      if (typeof value === "number") {
        if (value > 100) {
          return new Intl.NumberFormat("en-US", {
            style: "currency",
            currency: "USD",
            maximumFractionDigits: 0,
          }).format(value);
        }
        return value.toFixed(2);
      }
      return String(value);
    };

    const inputsList = Object.entries(inputs)
      .map(([key, value]) => `• ${key.replace(/([A-Z])/g, " $1").replace(/^./, s => s.toUpperCase())}: ${formatValue(value)}`)
      .join("\n");

    const resultsList = Object.entries(results)
      .map(([key, value]) => `• ${key.replace(/([A-Z])/g, " $1").replace(/^./, s => s.toUpperCase())}: ${formatValue(value)}`)
      .join("\n");

    // Send to user
    await resend.emails.send({
      from,
      to: email,
      subject: `Your ${toolDisplayName} Analysis - RentReadyTools`,
      html: analysisHtml || `
        <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto;">
          <h1 style="color: #0c4a47;">Your ${toolDisplayName} Analysis</h1>
          <p>Thanks for using RentReadyTools! Here's a summary of your analysis:</p>

          <h2 style="color: #0c4a47; font-size: 18px;">Your Inputs</h2>
          <pre style="background: #f5f5f5; padding: 16px; border-radius: 8px; white-space: pre-wrap;">${inputsList}</pre>

          <h2 style="color: #0c4a47; font-size: 18px;">Results</h2>
          <pre style="background: #f5f5f5; padding: 16px; border-radius: 8px; white-space: pre-wrap;">${resultsList}</pre>

          <hr style="border: none; border-top: 1px solid #e5e5e5; margin: 32px 0;" />

          <h2 style="color: #0c4a47; font-size: 18px;">Want a deeper analysis?</h2>
          <p>Our team can provide a free, personalized rental analysis for your property with local market data and recommendations.</p>

          <a href="https://rentreadytools.com/contact?reason=Free%20Analysis&source=${tool}"
             style="display: inline-block; background: #e9b060; color: #0c4a47; padding: 12px 24px; text-decoration: none; border-radius: 24px; font-weight: 600;">
            Get a Free Property Analysis
          </a>

          <p style="color: #666; font-size: 12px; margin-top: 32px;">
            This analysis was generated by RentReadyTools. Visit <a href="https://rentreadytools.com">rentreadytools.com</a> for more landlord tools.
          </p>
        </div>
      `,
    });

    // Notify admin of new lead
    await resend.emails.send({
      from,
      to: adminTo,
      subject: `[Lead] ${toolDisplayName} - ${email}`,
      text: [
        `New tool analysis saved!`,
        ``,
        `Email: ${email}`,
        `Tool: ${toolDisplayName}`,
        `Time: ${new Date().toLocaleString()}`,
        ``,
        `Inputs:`,
        inputsList,
        ``,
        `Results:`,
        resultsList,
      ].join("\n"),
    });

    return NextResponse.json({ success: true });
  } catch (error) {
    console.error("Send analysis error:", error);
    return NextResponse.json(
      { error: "Failed to send analysis email" },
      { status: 500 }
    );
  }
}
